[package]
name = "bite-log"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
anyhow = "1.0.70"
chrono = "0.4.24"
diesel = { version = "2.0.3", features = ["sqlite", "chrono"] }
libsqlite3-sys = { version = "0.25.2", features = ["bundled"] }
